eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8035

spring:
  application:
    name: Trip
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3307/ateliergl
    hikari:
      username: root
      password:

application:
  config:
    Datas-url: http://localhost:8090/users
    DataComp-url: http://localhost:8090/comp
    DataInv-url: http://localhost:8090/inv
