eureka:
  client:
    fetch-registry: false

server:
  port: 8222

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
            - id: vols
              uri: http://localhost:8020
              predicates:
                - Path=/vol/**
              filters:
                - AuthenticationFilter

            - id: reservations
              uri: http://localhost:8030
              predicates:
               - Path=/reservation/**
              filters:
                - AuthenticationFilter

            - id: security
              uri: http://localhost:8050
              predicates:
               - Path=/auth/**

