eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8093

spring:
  application:
    name: Trip
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3307/ateliergl
    hikari:
      username: root
      password:


application:
  config:
    DataTRIP-url: http://localhost:8090/api/vi/trips
    DataBLOG-url: http://localhost:8090/api/vi/blogs
    DataITIN-url: http://localhost:8090/api/vi/itinerarys
    DataCOMM-url: http://localhost:8090/api/vi/comments
